### PR TITLE
Fix some typos (found by codespell)

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by kba** [comment]
That file is copied from spec, the typos have since been fixed based on the PR in OCR-D/spec. Thanks!

**Comment by stweil** [comment]
Unrelated question: How is https://ocr-d.github.io/ managed, or more precisely, how can I send pull requests for that content?

**Comment by kba** [comment]
https://github.com/OCR-D/ocr-d.github.io should be public now.

**Comment by stweil** [comment]
Thank you!

**Pull request closed without merging**
